### ISSUE TITLE
Google-play module version conflict

### ISSUE THREAD

**Issue by a6wu** [UCSD/now-mobile#10]
App crashes on startup due to google-play-* version conflict in react-native-maps and react-native-google-analytics-bridge module.

Manual fix was to change the analytics version to 8.4.0 in react-native-google-analytics-bridge to match the version used in the maps module.

Need a better solution.

**Comment by i8wu** [comment]
Currently discussing a pull req with react-native-maps maintainers about bumping the google play version to 9+ instead of us dropping react-native-google-analytics-bridge down. https://github.com/lelandrichardson/react-native-maps/pull/533

**Comment by i8wu** [comment]
Pull request was accepted and published with newer version (0.8.2) on npm, new installations should not have this issue.
