### ISSUE TITLE
Map Card Stuck on Search

### ISSUE THREAD

**Issue by a6wu** [UCSD/now-mobile#100]
### Issue Description

Progress indicator displays but search results never appears; waited over 2 minutes. Test search was for "Geisel."

### Steps to Reproduce / Code Snippets

Open TestFlight version of app v2.4.0 (7). Scroll to Map card. Type in Geisel and tap Search on the keyboard.

#### Expected Results

Expect search results to appear below the map view.

### Additional Information

* Platform(s) (iOS, Android, or both?): iOS

**Comment by i8wu** [comment]
Hm, are you able to reproduce consistently? Just installed testflight fresh and searching Geisel or anything works.

**Comment by a6wu** [comment]
Resolved. It was the alphanumeric check on query string. Need to accommodate a broader query set.
