### ISSUE TITLE
Image Size Calculation Method

### ISSUE THREAD

**Issue by a6wu** [UCSD/now-mobile#11]
Some new methods have surfaced in which we can incorporate images into the app, and avoid a lot of now unnecessary calculations (mostly dealing with prm - pixel ratio modifier, and other aspect ratio calculations in the css file)

**Comment by c3bryant** [comment]
Working on a master fix for this which will improve scaling across all devices and eliminate floating point numbers in css

**Comment by c3bryant** [comment]
Initial task completed. Revisit again for v2.4 to refine
