### ISSUE TITLE
Trim JSON for Weather Feed

### ISSUE THREAD

**Issue by a6wu** [UCSD/now-mobile#12]
The weather feed currently has a lot of additional information that we currently aren't using and don't plan to use in the now@ app. The additional information increases the uncompressed size of the feed significantly

The request is to remove certain top-level keys from the feed. The keys we want to remove are:
- minutely
- hourly
- flags

The new feed name will be something like /prod/forecast-compact.json

**Comment by c3bryant** [comment]
This has been completed/tested in our AWS QA environment. Please see the GitLab repo for GrabWeatherFeed

Lines 55,56 of grab-weather-feed.js will need to be updated to match the AWS Prod environment paths

Note: we originally created this feed as a lambda service, called each time needed. This new GrabWeatherFeed lambda grabs the JSON feed from forecast.io and saves to S3. Recommend scheduling this to run every 1 hour

**Comment by c3bryant** [comment]
The WeatherServiceCompact lambda has been updated and tested on AWS QA, ready for implementation on AWS Production

**Comment by alexhwu** [comment]
Completed
