### ISSUE TITLE
Update JSON File for Events Feed

### ISSUE THREAD

**Issue by a6wu** [UCSD/now-mobile#17]
1) Have the appropriate team provide the events feed in json format
2) Include higher resolution images (large, thumb) for every event (about 10% of events have an image large enough to use for the Large size)
3) Include a complete/full Description
4) Include the event category, 

Desired Feed Schema:
{
    "EventID": "24749",
    "EventImageLg": "http://studentevents.ucsd.edu/article_images/sample_lg.jpg",       // High res event image (1080px wide recommended, any height)
    "EventImageSm": "http://studentevents.ucsd.edu/article_images/sample_sm.jpg",       // Low res thumbnail (480x wide recommended, any height)
    "EventTitle": "Art & Soul: Decorate Your Grad Cap!",
    "EventCategory": "art",                                                             // example Types: athletic, entertainment, food, art, etc
    "EventLocation": "The Zone",
    "EventDescription": "Top off your graduation with a uniquely decorated grad cap! Workshops are free; all supplies and materials provided. Space is limited and is first come, first served. ",  // Full event description
    "EventURL": "http://zone.ucsd.edu",
    "EventDate": [    // null if an Ongoing Event
        "Mon, May 23, 2016 11:00AM - 12:00PM"
        "Tue, May 24, 2016 11:00AM - 12:00PM"
    ],
    "EventContact": "zone@ucsd.edu",
    "EventType": "Specific",        // Specific or Ongoing
},

**Comment by c3bryant** [comment]
Dan has updated the Student Events feed to roughly match our format/data requested

http://studentevents.ucsd.edu/jsonfeed

**Comment by c3bryant** [comment]
@i8wu feed implementation looks good, sending this your way to work with Alex to:
1. get the events-service lambda and api gateway setup on aws prod
2. update AppSettings w/ prod url

**Comment by a6wu** [comment]
Completed.
