### ISSUE TITLE
Use Redux

### ISSUE THREAD

**Issue by a6wu** [UCSD/now-mobile#26]
Pros/cons of using redux?

**Comment by srkirkland** [comment]
@a6wu Pro is that it gets most of your state management out of your components.  With the cards approach there is not a ton of crossover so it might not pay gigantic dividends but once you start dealing with preferences, hide/show cards, and especially user management I think you won't want to live without redux.  Also I'd suggest using something like Redux Thunk to move some/all of the data access methods out of the components as well.

Another con is the setup is a little tricky and redux itself is wordy, though the instructions online are decent and I'm happy to help and/or show what a "real world" redux setup looks like.

**Comment by c3bryant** [comment]
Redux phase 1 is now in from [PR 67](https://github.com/UCSD/now-mobile/pull/67)
