### ISSUE TITLE
Code Comments Guideline

### ISSUE THREAD

**Issue by a6wu** [UCSD/now-mobile#27]
Draft guidelines for commenting code

**Comment by c3bryant** [comment]
Proposed acceptable commenting formats below. These are based on a rant from Linus earlier this year which I tend to agree with

Type A:
`/* This is a comment */`

Type B:
```
/* 
* This is also a comment, but it can now be cleanly 
* split over multiple lines 
*/
```

Type C:
`// This can be a single line. Or many. Your choice.`

Type D:
```
/* This is an alternate multi-line format 
that isn't horrible, but not kernel style */
```

(no) 
/* Lorem ipsum dolor sit amet
* consectetur adipiscing elit
*/

(no-no-no) 
/* This is also very nasty 
* and visually unbalanced */

**Comment by srkirkland** [comment]
@a6wu @c3bryant I think this would be a great thing if you used an ESLint file and then anyone working on the repository would also know to follow the same rules (their linter would yell at them if they used the wrong styles).  For reference, I really like the AirB&B javascript style guide (https://github.com/airbnb/javascript) and there is an ESLint ruleset you can use that would be great for ensuring contributors conform as well.

**Comment by c3bryant** [comment]
Thanks @srkirkland for [PR 61](https://github.com/UCSD/now-mobile/pull/61), we will use that going forward
