### ISSUE TITLE
Use CodePush

### ISSUE THREAD

**Issue by a6wu** [UCSD/now-mobile#28]
Use CodePush service to enable updates outside the app stores' approval process. https://microsoft.github.io/code-push/

**Comment by i8wu** [comment]
https://github.com/Microsoft/react-native-code-push
Following github documentation is pretty straightforward. Only thing I had an issue with is having MyApp = codePush(MyApp); before AppRegistry.registerComponent...

**Comment by c3bryant** [comment]
Please remove or disable CodePush for the pending v2.3 build/Pikachu milestone

**Comment by i8wu** [comment]
Removed for now 221776b873170c3f3b6a770a6246c26b022f2bbf

**Comment by c3bryant** [comment]
Please enable CodePush for the upcoming v2.4 build/Charizard milestone

**Comment by c3bryant** [comment]
codepush is enabled for 2.4-rc
