### ISSUE TITLE
Rework Show More Action

### ISSUE THREAD

**Issue by a6wu** [UCSD/now-mobile#33]
Rework the Show More News and Show More Events feature. Options?

**Comment by c3bryant** [comment]
This will also apply to the Dining card and possibly the Nearby card as well

The proposed solution is to implement a 'View All' button in these cases, which take the user to a dedicated list view with all results.

**Comment by i8wu** [comment]
3d07607db1df00a3cefad5476d5bf770c1a64e4b implements a list view of cards that is triggered instead of the expanding list.

**Comment by c3bryant** [comment]
Please add 'View All' to Dining card after Dining Card has been broken out

**Comment by c3bryant** [comment]
View All added to dining card, need to revisit Nearby card to see if this is warranted after Search is added
