### ISSUE TITLE
Static Shuttle Schedule

### ISSUE THREAD

**Issue by a6wu** [UCSD/now-mobile#34]
Show static shuttle schedule for the day when live data is not available.

**Comment by i8wu** [comment]
https://www.ucsdbus.com/MobileInformation Can text ucsd <stopid> to 41411 for shuttle stop info. @a6wu look into if there's a different backend for this so we can use as redundancy on ShuttleFeed.

**Comment by i8wu** [comment]
There doesn't seem to be a static schedule...maybe if shuttle feed is down we'll just have to notify user that it's down?

**Comment by alexhwu** [comment]
I wonder if there's a schedule api we can call. But I found this page here for the campus loop: http://transportation.ucsd.edu/shuttles/campus-loop.html

**Comment by i8wu** [comment]
Not sure if it'd be useful, but we can have something like bus will be arriving within 15mins or within 25mins when it's later? Or we can ask transportation for a better static schedule? 

I also think we should definitely let the user know if we are unable to get live shuttle data, otherwise the user might just think the app isn't good at giving out shuttle times

**Comment by alexhwu** [comment]
I contacted transportation and current response is that the schedule data comes through email and then gets added to the web page. Still trying to see who has access to the raw data. For displaying an indicator of when the data is not live -yes, good idea.

**Comment by i8wu** [comment]
Does transportation not have a somewhat set schedule though? I know shuttles sometimes wait at certain stops for 5 or 10 mins, and I would assume they do so because they are ahead of schedule?

**Comment by alexhwu** [comment]
Yes, I think they have a set schedule as well. The website listed above is what we have for now. We'll have to find out who the source is and hopefully be able to get to the data directly.

**Comment by i8wu** [comment]
What if we started a weeklong/monthlong analysis on how long it takes buses to get between stops and use that to display estimated 'static' arrival times? Or ask transportation if they have estimated time it takes to get between stops?

For example: Clockwise loop leaves Peterson at 7:15, ETA for Muir Apartments 3mins
