### ISSUE TITLE
Welcome Week Event Stuck on Scroll

### ISSUE THREAD

**Issue by a6wu** [UCSD/now-mobile#38]
### Issue Description

When scrolling through the welcome week event list, an even item will become stuck as an overlay over the list even as the scrolling continues.

### Steps to Reproduce / Code Snippets

Tap into Welcome Week and scroll up through events.

### Additional Information

* React Native version: 0.31.0
* Platform(s) (iOS, Android, or both?): iOS
* Operating System (macOS, Linux, or Windows?): iOS

**Comment by i8wu** [comment]
Was a problem with using EventIDs from our feed, adjusted lambda to provide our own ID for each event and used that for listview.

**Comment by i8wu** [comment]
Was a problem with using EventIDs from our feed, adjusted lambda to provide our own ID for each event and used that for listview.
