### ISSUE TITLE
2.2: Android: Crash on Home view when interacting with Nearby card map

### ISSUE THREAD

**Issue by c3bryant** [UCSD/now-mobile#40]
### Issue Description

Nexus 5 running Android 6.0.1 is crashing on Home view when interacting with Nearby card map; likely caused from invalid Google Play Services version

### Steps to Reproduce / Code Snippets

1. Load app version 2.2 on Android and scroll down to Nearby card on Home view.
2. Attempt to interact with Nearby map
3. Crash

Device					htc_himaul
Android OS Version		23
App Version Name			1
App Version Code			2
Exception Class Name		java.lang.IllegalStateException
Exception Message		Tried to use permissions API while not attached to an Activity.
Throwing Method Name		getPermissionAwareActivity
Throwing File Name		PermissionsModule.java
Throwing Class Name		com.facebook.react.modules.permissions.PermissionsModule
Throwing Line Number		139

### Additional Information

* React Native version: 0.31
* now@ucsd version: 2.2
* Platform(s) (iOS, Android, or both?): Android Nexus 5 6.0.1 API 23
* Operating System (macOS, Linux, or Windows?):

**Comment by i8wu** [comment]
ef024f56af4514634a287b1ce216708d59d5fc06 should be a fix for this. Need some testing.

**Comment by c3bryant** [comment]
Verified this issue was resolved for Android branch v2.2playhotfix

New issue reported, seems related:
- Getting an error when updating to 2.3 alpha from 2.2 version.
- java.lang.VerifyError: com/google/android/gms/maps/MapsInitializer

**Comment by i8wu** [comment]
@c3bryant issue is being cause by conflicting google-play versions in the various node_modules we are using.

**Comment by c3bryant** [comment]
issue resolved in 2.3+
