### ISSUE TITLE
Revisit google analytics view tracking

### ISSUE THREAD

**Issue by c3bryant** [UCSD/now-mobile#43]
### Issue Description

Revisit google analytics view tracking to ensure all views are being tracked correctly, and that detail views pass the full title to GA

### Additional Information

* React Native version: 0.33
* Platform(s) (iOS, Android, or both?): both
* Operating System (macOS, Linux, or Windows?): all

**Comment by i8wu** [comment]
8277dc306c0b04e0bef56bd074a6994027188c8d adds ga tracking to most views, dining tracking may be need to updated as dining view changes

**Comment by c3bryant** [comment]
fixed a few last issues in [22e5b59](https://github.com/UCSD/now-mobile/commit/22e5b5957744d44ff12ef5c164f989298d9eee3b)
closing
