### ISSUE TITLE
Rename TopStories to News

### ISSUE THREAD

**Issue by c3bryant** [UCSD/now-mobile#46]
### Issue Description

Rename TopStories to News

TopStories should be changed to News as we are using the full news feed not the TopStories feed

### Additional Information

* React Native version: any
* Platform(s) (iOS, Android, or both?): all
* Operating System (macOS, Linux, or Windows?): all

**Comment by i8wu** [comment]
done 93e3f12de3d5266b58d4c88ec2fce6a6ad06fc84
