### ISSUE TITLE
Incorporate 3rd party dining locations into hdh dining feed

### ISSUE THREAD

**Issue by c3bryant** [UCSD/now-mobile#47]
### Issue Description

The current dining feed provided by HDH does not include a number of 3rd party dining establishments on campus. Investigate ways to incorporate these locations into the master Dining feed.

For the first phase we would like to be able to add 3rd party dining locations (Rubios, Subway, etc) to the Dining feed to provide basic information such as Name, Location (with directions) and Open Hours

### Additional Information

* React Native version: any
* Platform(s) (iOS, Android, or both?): all
* Operating System (macOS, Linux, or Windows?): all

**Comment by i8wu** [comment]
Probably need to contact whoever manages PC? UCAB?
http://universitycenters.ucsd.edu/eat.php
https://ucab.ucsd.edu/

**Comment by c3bryant** [comment]
Added to v2.3-rc
