### ISSUE TITLE
Background color on Feedback (WebWrapper) does not match primary background color

### ISSUE THREAD

**Issue by c3bryant** [UCSD/now-mobile#49]
### Issue Description

Something happened on the Feedback form that caused the top/bottom portions of the form to not match the rest of the background on the page. Investigate and fix

### Additional Information

* React Native version: all
* Platform(s) (iOS, Android, or both?): both
* Operating System (macOS, Linux, or Windows?): both

**Comment by i8wu** [comment]
https://eforms.ucsd.edu/data/form_175631/css/view.css that is why, need to figure out how to remove bg image, will look into further...

**Comment by i8wu** [comment]
0489583acb0d3d069d747015f85c2575e33187ac fixes this

I think I would prefer if our feedback form was native instead of a wrapper though...any good reason why it shouldn't be?

**Comment by c3bryant** [comment]
Thanks for the fix.

With the form, the main problem at the moment is that they want us to use eforms.ucsd to keep all of the data centrally localized. The secondary problem would be being unable to update the form on the fly without a version or code push.

I'm going to close this out and add an issue to look into API accessibility for eforms.ucsd
