### ISSUE TITLE
Investigate API accessibility for eforms.ucsd

### ISSUE THREAD

**Issue by c3bryant** [UCSD/now-mobile#50]
### Issue Description

Investigate eforms.ucsd functionality; determine if there is a robust enough set of APIs to convert the current Now@ form into a native form, rather than using the WebWrapper view in place now.

### Additional Information

* React Native version: all
* Platform(s) (iOS, Android, or both?): all
* Operating System (macOS, Linux, or Windows?): all

**Comment by i8wu** [comment]
d52220d7f112b179fb544277555ea8381515bf7b implements a native view that submits the eform via post request
