### ISSUE TITLE
Unnecessary Key

### ISSUE THREAD

**Issue by jpknoll** [UCSD/now-mobile#60]
Call on 
https://github.com/UCSD/now-mobile/blob/dev/app/views/Home.js#L254

The key value is unnecessary. Additionally, it's set randomly per call, which means that react will replace the card per draw.

**Comment by i8wu** [comment]
I was getting a warning from react native that these items needed unique keys, so I put that in. It was for android and I don't believe Charles was seeing it on iOS. If we can take it out without the warning reappearing I'd be all for that.

**Comment by jpknoll** [comment]
Which is fine, but your keys should stay the same per render call. React uses the key to compare application state.

I'd suggest something like:

`key='weather'`

**Comment by i8wu** [comment]
That does sound much better than what I put in. Could you try putting that in and testing if you have time? I can get to it later today if not. Thanks!
