### ISSUE TITLE
Location permissions not handled if user doesn't allow access

### ISSUE THREAD

**Issue by srkirkland** [UCSD/now-mobile#63]
### Issue Description

If the user doesn't allow location access, the app just fails on most cards without any indication of why, and the `this.state.locationPermission` is set to authorized for some reason so the cards are not able to determine what is happening

### Steps to Reproduce / Code Snippets

Install the app and when it asks for location permissions click "don't allow"

#### Expected Results

Either we decide location permissions are required and show a global "please go enable location permissions" message, or at least redo permissions so the cards can determine what to do in the absence of location info.

### Additional Information

* React Native version: Current
* Platform(s) (iOS, Android, or both?): iOS (though could be both)
* Operating System (macOS, Linux, or Windows?): OSX

**Comment by c3bryant** [comment]
Adding a few notes on how things are setup now-

Location Required
Shuttle
Nearby
Dining

Location Not Required
Weather
Surf
Events
News

We had a discussion a while back on this, and would really like to have the app be fully functional without needing location permissions for anything to 'work'

Some ways to accomplish this were:

- For the Shuttle card, when location permissions are disabled, show static data of the general shuttle route times/eta's (this is currently in the works for when the Shuttle API goes down like it did today)
- For the Nearby card, possibly rename the card entirely or just for users with permissions disabled. List locations not by nearest but based on a simple ranking system (most prominent first, i.e. Geisel Library, Price Center, etc)
- For the Dining card - disable the distance in miles to destination; order results not by closest but by alphanumeric

The Nearby and Dining cards (and ultimately but not yet the Shuttle card) have buttons to get directions which take you out to your native mapping application (Apple Maps, Google Maps) and they can handle the permissions from there

**Comment by srkirkland** [comment]
@c3bryant Sounds good to me, though right now there is no way for those cards to know that location permissions are disabled, which is my main issue.  If the cards did know then they could handle it in different ways.  Ideally the home.js file could handle this like it is now but then use Redux or something to notify the cards what is happening with location, then each card could do something like you mention in their "no location" modes.  Also remember that since this is open source make sure when you talk about "static data of shuttles" you don't actually store that data in the app itself since it'll be different for every campus.  It could be downloaded on first use and then stored in async storage for a long time and that would be a good solution.

**Comment by c3bryant** [comment]
Now that Redux is in place, added  [#79](https://github.com/UCSD/now-mobile/issues/79) to revisit this and include it in the next milestone
