### ISSUE TITLE
Map Search

### ISSUE THREAD

**Issue by i8wu** [UCSD/now-mobile#66]
Need to implement map search.
Refer to #52 for search api ~~We'll be using CampusBird search API~~
Possible nice feature: https://github.com/l-urence/react-native-autocomplete-input

**Comment by i8wu** [comment]
Implemented on mapsearch branch, full map view is using https://github.com/ninamanalo19/react-native-sliding-up-panel , which has some performance conflict with mapview. I put in a pull request for a fix and we're waiting on a response from the owner. If we don't get a response we could just import my fork into the app.

**Comment by c3bryant** [comment]
added to 2.4-rc, closing
