### ISSUE TITLE
Nonstop loading animation

### ISSUE THREAD

**Issue by a6wu** [UCSD/now-mobile#7]
### Issue Description

Shuttle card continually shows the loading animation

### Steps to Reproduce / Code Snippets

On home screen when app launches, the shuttle card loading animation does not go away, and the shuttle data does not populate.

#### Expected Results

Shuttle data appears and the loading animation goes away

### Additional Information

* React Native version: 0.31.0
* Platform(s) (iOS, Android, or both?): Android
* Operating System (macOS, Linux, or Windows?): On LG3 Phone

**Comment by i8wu** [comment]
is this still a problem with v2.3 android? @a6wu

**Comment by c3bryant** [comment]
Fixed in 2.3-rc
