### ISSUE TITLE
Add Quick Links card to incorporate popular links from old app

### ISSUE THREAD

**Issue by c3bryant** [UCSD/now-mobile#76]
### Issue Description

Add a Quick Links card to incorporate popular links from old app

The card should feature the top 4 results, and have a 'View All' button similar to News or Events cards

Each quick-links line item should take the user out of the app, and have room for a Title, Short description, and possibly an icon or version of the old icon floating to the right.

Current feed in dev for UCSD: https://s3-us-west-2.amazonaws.com/ucsd-mobile/dev/ucsd-quicklinks.json

**Comment by wtsucsd** [comment]
done

**Comment by c3bryant** [comment]
done
