### ISSUE TITLE
Flash of black screen

### ISSUE THREAD

**Issue by a6wu** [UCSD/now-mobile#8]
### Issue Description

Screen on OnePlusOne phone flashes black for an instant on app launch.

### Steps to Reproduce / Code Snippets

Launch app on OnePlusOne phone. Screen flashes when the home view loads.

#### Expected Results

Should not have a flash of black screen.

### Additional Information

* React Native version: 0.31.0
* Platform(s) (iOS, Android, or both?): Android
* Operating System (macOS, Linux, or Windows?): On OnePlusOne phone

**Comment by i8wu** [comment]
Seems to be fixed now, probably by RN update and maps update.
