### ISSUE TITLE
Dining Missing Special Hours

### ISSUE THREAD

**Issue by a6wu** [UCSD/now-mobile#81]
### Issue Description

Certain dining locations do not have the special hours displayed, e.g. 64 Degrees dining location.

#### Expected Results

Should have special hours displayed. For example, http://hdh.ucsd.edu/mobile/dining/locationdetails.aspx?l=64, has the Veterans Day hours listed.

**Comment by c3bryant** [comment]
done - special hours for hdh run dining locations will now show up dynamically in the dining card, dining list, and dining detail views
