### ISSUE TITLE
Script for To Keep Key Values Out of Repo

### ISSUE THREAD

**Issue by alexhwu** [UCSD/now-mobile#89]
Create a script that is run to fill in select string values. This will help keep the repository clear of production and other sensitive values.

String values for the script to replace:

- Google Analytics Property ID
- CodePush Key
- Google Map Developer API Key

**Comment by c3bryant** [comment]
Added a readme to /scripts/ with all known replacements we will need to incorporate

1) Create a folder in your home directory ".nowapp"

2) In your ".nowapp" folder, create a file "env.js" with the following content:

	var APP_NAME = 'now-mobile';
	var APP_SHORTNAME = 'now-mobile';	// Text shown under your App Icon

	var CODEPUSH_IOS_KEY_PROD = 'iOS Production Key Here';
	var CODEPUSH_IOS_KEY_STG = 'iOS Staging Key Here';
	var CODEPUSH_ANDROID_KEY_STG = 'Android Staging Key Here';
	var CODEPUSH_ANDROID_KEY_PROD = 'Android Production Key Here';

	var GOOGLE_ANALYTICS_ID = 'Google Analytics ID Here';
	var GOOGLE_MAPS_API_KEY = 'Google Maps API Key Here';

	exports.APP_NAME = APP_NAME;
	exports.APP_SHORTNAME = APP_SHORTNAME;

	exports.CODEPUSH_IOS_KEY_PROD = CODEPUSH_IOS_KEY_PROD;
	exports.CODEPUSH_IOS_KEY_STG = CODEPUSH_IOS_KEY_STG;
	exports.CODEPUSH_ANDROID_KEY_STG = CODEPUSH_ANDROID_KEY_STG;
	exports.CODEPUSH_ANDROID_KEY_PROD = CODEPUSH_ANDROID_KEY_PROD;

	exports.GOOGLE_ANALYTICS_ID = GOOGLE_ANALYTICS_ID;
	exports.GOOGLE_MAPS_API_KEY = GOOGLE_MAPS_API_KEY;

**Comment by c3bryant** [comment]
Remaining:
- Script to handle Google Analytics ID
- Script to handle Google Maps API Key
- Script to handle App Name
- Script to execute all 4 replacement scripts

**Comment by a6wu** [comment]
replace_all.js sometimes does not correctly update files. May be due to async nature. Look at putting in verification after the script completes.

**Comment by a6wu** [comment]
Completed.
