### ISSUE TITLE
Android emulator API version performance difference

### ISSUE THREAD

**Issue by a6wu** [UCSD/now-mobile#9]
### Issue Description

Noticeable performance difference between Android API v22 and v23 on the emulator
### Steps to Reproduce / Code Snippets

Setting the target  AndroidManifest.xml, run the emulator for Nexus 5. Target API of v22 is noticeably slower in performance compared to v23.
#### Expected Results

Performance should be on par between the two versions.
### Additional Information
- React Native version: 0.31.0
- Platform(s) (iOS, Android, or both?): Android
- Operating System (macOS, Linux, or Windows?): Emulator

**Comment by i8wu** [comment]
Tried reproducing issue with current dev build, performance seems comparable between both. @a6wu when you have time could you try reproducing? Should be able to close if we're unable to reproduce.

**Comment by a6wu** [comment]
Thanks @i8wu. Closing.
