### ISSUE TITLE
Bug: Crash on initial app load after install

### ISSUE THREAD

**Issue by c3bryant** [UCSD/now-mobile#92]
### Issue Description

Seeing an app crash only on initial load from a fresh app install

There isn't much in the stack trace but we were able to track the root cause back to `<GeoLocationContainer />` in app/index.js

### Steps to Reproduce / Code Snippets

1) Remove app from sim/device
2) Install app on sim/device from branch v2.4-rc
3) This part varies slightly (possibly due to timers firing):
3a) 4/5 times the following error comes up right away, prior to the Home view loading
3b) 1/5 times Home view and modal views load as normal - the same error comes up after interacting with Allow Location access popup

![screen shot 2016-11-23 at 8 56 21 am](https://cloud.githubusercontent.com/assets/15112294/20572945/76a4bb3c-b162-11e6-8cbe-3d941b081080.png)

### Additional Information
* Platform(s) (iOS, Android, or both?): both

**Comment by i8wu** [comment]
Seems like the culprit was
```
// fire immediately on different thread
this.setTimeout(
this.getPermission(),
100
);
```
Moving this.getPermission() out of the timeout doesn't seem to cause any issues.
@jpknoll I think the idea for the timeout was for performance? But the app seems to be fine with taking it out, any thoughts/arguments on why we should try keeping the timeout?

**Comment by c3bryant** [comment]
closing this out as the issue is resolved, @jpknoll let us know if you have any last thoughts
