### ISSUE TITLE
Setup production lambda/api gateway for map search

### ISSUE THREAD

**Issue by c3bryant** [UCSD/now-mobile#93]
### Issue Description

Setup a production lambda and api gateway for map search

Sample query: http://act.ucsd.edu/maps/textsearch.json?region=0&q=Geisel

API cache/TTL can be set to max at 1h (ideally it would be longer (1-7 days) if that ever becomes an option)

**Comment by a6wu** [comment]
@c3bryant @i8wu https://xgu9qa7gx4.execute-api.us-west-2.amazonaws.com/prod/map/search?query=market&region=0

**Comment by c3bryant** [comment]
verified, closing
