### ISSUE TITLE
Map Search: Map re-zooms in every 5 seconds

### ISSUE THREAD

**Issue by c3bryant** [UCSD/now-mobile#95]
On iOS (Apple Maps), after the user searches for a location, and then clicks on the result to show the marker on the map, every 5 seconds the map re-zooms into the center point between the user and the destination

**Comment by i8wu** [comment]
Looking into it

**Comment by i8wu** [comment]
Issue was being cause my gps location state being update, added invalidation to make sure it doesn't happen. 10efd33961e14bbad1b2f73bfe80b814bc246ed5

@c3bryant if you can verify it isn't happening anymore we should be able to close this.

**Comment by c3bryant** [comment]
looks good thanks Ivan
