### ISSUE TITLE
Map Search: API Caching

### ISSUE THREAD

**Issue by i8wu** [UCSD/now-mobile#96]
AWS MAP_SEARCH_API is caching result which is a problem because new searches returns and old response. @a6wu

**Comment by a6wu** [comment]
@i8wu I've removed the cache

**Comment by i8wu** [comment]
After some painstaking trial and error I've gotten API caching working with query strings.
[Dev API URL](https://gzsrqw8v9e.execute-api.us-west-2.amazonaws.com/dev/map/search?region=0&query=physics)

Basically:
1. Enable API cache in Stages
2. Add query string parameters to Resources > GET > Method Request and check caching

Additional steps if above didn't work:
-Flush API cache
-Clone API and re-deploy (if you get 500 error try re-adding lambda method in Resources > GET > Method Request)
